# Generated by Django 4.0.4 on 2022-05-20 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chat_chatroom_comment_hashtag_post_story_storyimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recentsearch',
            name='search_hashtag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hashtag'),
        ),
        migrations.AlterField(
            model_name='recentsearch',
            name='search_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_profile', to='api.profile'),
        ),
    ]
