# Generated by Django 4.0.4 on 2022-05-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_recentsearch_search_hashtag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroomprofile',
            name='mute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatroomprofile',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
