# Generated by Django 4.0.4 on 2022-05-23 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_profile_avatar_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower_profile', 'followee_profile')},
        ),
    ]
