# Generated by Django 4.0.4 on 2022-05-23 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_follow_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='followee_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_followees', to='api.profile'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_followers', to='api.profile'),
        ),
    ]
