# Generated by Django 4.0.4 on 2022-05-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_follow_followee_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('PU', 'Public'), ('PR', 'Private')], default='PU', max_length=2),
        ),
    ]
