# Generated by Django 4.0.4 on 2022-05-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_post_type_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='body',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='code',
            field=models.CharField(default='', max_length=11, unique=True),
        ),
    ]
