# Generated by Django 4.0.4 on 2022-05-26 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_post_video_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='video_image',
            new_name='video_thumbnail',
        ),
    ]
