# Generated by Django 4.0.4 on 2022-05-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_post_comments_count_post_likes_count'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['code'], name='api_post_code_19502b_idx'),
        ),
    ]
