# Generated by Django 4.0.4 on 2022-05-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_commentlike_likes_count_comment_likes_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='like_profiles',
            field=models.ManyToManyField(related_name='like_profile', through='api.StoryLike', to='api.profile'),
        ),
        migrations.AddField(
            model_name='story',
            name='view_profiles',
            field=models.ManyToManyField(related_name='view_profile', through='api.StoryView', to='api.profile'),
        ),
    ]
