# Generated by Django 4.0.4 on 2022-06-02 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_follow_unique_together_follow_follower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postlike_profile', to='api.profile'),
        ),
    ]
