# Generated by Django 4.0.4 on 2022-06-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_notification_comment_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
