# Generated by Django 4.0.4 on 2022-06-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_postimage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='online',
            field=models.IntegerField(default=0),
        ),
    ]
