# Generated by Django 4.0.4 on 2022-06-13 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_profile_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='chat_room',
            new_name='chatroom',
        ),
        migrations.RenameField(
            model_name='chatroomprofile',
            old_name='chat_room',
            new_name='chatroom',
        ),
    ]
