# Generated by Django 4.0.4 on 2022-06-13 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_rename_chat_room_chat_chatroom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroomprofile',
            old_name='mute',
            new_name='is_mute',
        ),
    ]
