# Generated by Django 4.0.4 on 2022-06-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_rename_mute_chatroomprofile_is_mute'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroomprofile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
