# Generated by Django 4.0.4 on 2022-06-14 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_rename_last_activity_profile_last_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroomprofile',
            old_name='read_chat',
            new_name='last_read_chat',
        ),
    ]
