# Generated by Django 4.0.4 on 2022-06-17 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_rename_read_chat_chatroomprofile_last_read_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='reply_to_chat',
            new_name='reply_to',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='reply_to_comment',
            new_name='reply_to',
        ),
    ]
