# Generated by Django 4.0.4 on 2022-06-20 06:08

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_rename_chat_chatreaction_reply_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
