# Generated by Django 4.0.4 on 2022-06-21 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_view_page_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
