# Generated by Django 4.0.4 on 2022-06-21 04:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_profile_last_view_page_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_view_page_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 4, 41, 54, 590639, tzinfo=utc)),
        ),
    ]
