# Generated by Django 4.0.4 on 2022-07-15 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_rename_type_profile_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes_count',
        ),
        migrations.AlterField(
            model_name='storyview',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_view', to='api.profile'),
        ),
        migrations.AlterField(
            model_name='storyview',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_view', to='api.story'),
        ),
    ]
