# Generated by Django 4.0.4 on 2022-08-02 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_remove_comment_likes_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentsearch',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_comments', to='api.comment'),
        ),
    ]
