# Generated by Django 4.0.4 on 2022-08-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_postimage_options_chat_share_post_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='reply_story_img',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('N', 'normal'), ('S', 'share_post'), ('R', 'reply_story')], default='N', max_length=2),
        ),
    ]
