# Generated by Django 4.0.4 on 2022-08-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_chat_reply_story_img_alter_chat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_active',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
