# Generated by Django 4.0.4 on 2022-08-20 07:45

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_profile_last_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='images'),
        ),
    ]
