# Generated by Django 4.0.4 on 2022-05-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_notification_body_alter_chatroom_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
