# Generated by Django 4.0.4 on 2022-05-20 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_chat_postseen_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chat',
            name='reply_to_chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.chat'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply_to_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.comment'),
        ),
    ]
