# Generated by Django 4.0.4 on 2022-05-20 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_chat_reply_to_chat_alter_notification_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentsearch',
            name='search_hashtag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hashtag'),
        ),
        migrations.AlterField(
            model_name='recentsearch',
            name='search_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_profile', to='api.profile'),
        ),
    ]
