# Generated by Django 4.0.4 on 2022-05-20 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_chatroomprofile_mute_chatroomprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='name',
        ),
    ]
