from django.urls import path
from . import views
from .views import MyTokenObtainPairView

from rest_framework_simplejwt.views import (
    TokenRefreshView,
)

urlpatterns = [
    path('profiles/', views.my_profile, name="my-profile"),
    path('profiles/username/<str:username>/', views.get_profile, name="get-profile"),
    path('profiles/username/<str:username>/follower/', views.get_follower, name="get-follower"),
    path('profiles/username/<str:username>/following/', views.get_following, name="get-following"),
    path('profiles/suggest/', views.get_suggest_profile, name="get-suggest-profile"),
    path('profiles/search/<str:keyword>/', views.get_search_profile, name="get-search-profile"),
    path('profiles/chat/suggest/', views.get_chat_suggest_profile, name="get-chat-suggest-profile"),
    path('posts/code/<str:code>/', views.process_post, name="process-post"),
    path('posts/code-and-recent/<str:code>/', views.get_posts_by_code_and_recent, name="process-post"),
    path('posts/username/<str:username>/', views.get_posts, name="get-posts"),
    path('posts/', views.create_post, name="create-post"),
    path('posts/current-user/', views.get_posts_current_user, name="get-posts-current-user"),
    path('posts/current-user/new/', views.get_new_posts_current_user, name="get-new_posts-current-user"),
    path('posts/tag-popular/<str:tag>/', views.get_posts_by_tag_popular, name="get-posts-by-tag-popular"),
    path('posts/tag-recent/<str:tag>/', views.get_posts_by_tag_recent, name="get-posts-by-tag-recent"),
    path('posts/suggest/', views.get_suggest_posts, name="get-suggest_posts"),
    path('posts/like-unlike/', views.like_unlike_post, name="like-unlike-post"),
    path('posts/like-profile/code/<str:post_code>/', views.get_post_like_profile, name="post-like-profile"),
    path('posts/save-unsave/', views.save_unsave_post, name="save-unsave-post"),
    path('posts/saved/', views.get_saved_post, name="get-saved-post"),
    path('hashtags/search/<str:keyword>/', views.search_hashtag, name="search-hashtag"),
    path('recent-searches/', views.process_recent_search, name="recent-search"),
    path('recent-searches/<int:pk>/', views.delete_search, name="delete-search"),
    path('comments/', views.create_comment, name="create-comment"),
    path('comments/<int:pk>/', views.delete_comment, name="delete-comment"),
    path('comments/post-code/<str:post_code>/', views.get_comments, name="get-comments"),
    path('comments/reply-comments/<str:comment_id>/', views.get_reply_comments, name="get-reply-comments"),
    path('comments/like-unlike/', views.like_unlike_comment, name="like-unlike-comment"),
    path('comments/like-profile/<int:pk>/', views.get_comment_like_profile, name="comment-like-profile"),
    path('stories/', views.create_story, name="create-get-story"),
    path('stories/current-user/', views.get_stories_current_user, name="get-stories-current-user"),
    path('stories/<int:pk>/', views.delete_story, name="delete-story"),
    path('stories/like-unlike/', views.like_unlike_story, name="like-unlike-story"),
    path('stories/view/', views.view_story, name="view-story"),
    path('stories/reply/', views.reply_story, name="reply-story"),
    path('stories/<int:pk>/activity/', views.get_story_activity, name="get-story-activity"),
    path('follows/follow-unfollow/', views.follow_unfollow, name="follow-unfollow"),
    path('token/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('signup/', views.user_signup, name='signup'),
    path('signup/validate/', views.validate_user_signup, name='validate-signup'),
    path('notification/', views.get_notification, name='get-notification'),
    path('notification/seen/', views.seen_notification, name='seen-notification'),
    path('chatroom/', views.get_create_chat_room, name='get-create-chat-room'),
    path('chatroom/seen/', views.get_chat_seen, name='get-chat-seen'),
    path('chatroom/share/', views.share_post_to_chat, name='share-post-to-chat'),
    path('chatroom/<int:pk>/', views.update_chat_room, name='create-chat-room'),
    path('chatroom/<int:pk>/promote-demote-admin/', views.promote_demote_admin, name='promote-demote-admin'),
    path('chatroom/<int:pk>/chat/', views.get_chat_list, name='get-chat-list'),
    path('chat/<int:pk>/reaction/', views.get_reaction_list, name='get-reaction-list'),
] 